In [1]:
# Q1. Create a 5×5 NumPy matrix containing numbers from 1 to 25 and print:
# First row, Last column, Diagonal elements

import numpy as np

matrix = np.arange(1, 26).reshape(5, 5)

print("Matrix:\n", matrix)
print("First Row:", matrix[0])
print("Last Column:", matrix[:, -1])
print("Diagonal Elements:", np.diag(matrix))

Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First Row: [1 2 3 4 5]
Last Column: [ 5 10 15 20 25]
Diagonal Elements: [ 1  7 13 19 25]


In [2]:
# Q2. Create two 3×3 matrices and perform addition, subtraction, and multiplication

import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

print("Addition:\n", A + B)
print("Subtraction:\n", A - B)
print("Matrix Multiplication:\n", np.dot(A, B))

Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [3]:
# Q3. Create an array from 1 to 100 and print numbers divisible by 3

import numpy as np

arr = np.arange(1, 101)

print(arr[arr % 3 == 0])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [4]:
# Q4. Create a 4×4 matrix and replace all even numbers with 0

import numpy as np

matrix = np.arange(1, 17).reshape(4, 4)

matrix[matrix % 2 == 0] = 0

print(matrix)

[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [5]:
# Q5. Create a 5×5 random matrix and find max, min, mean, median

import numpy as np

matrix = np.random.randint(1, 100, (5, 5))

print("Matrix:\n", matrix)
print("Maximum:", np.max(matrix))
print("Minimum:", np.min(matrix))
print("Mean:", np.mean(matrix))
print("Median:", np.median(matrix))

Matrix:
 [[21 85 94 31 79]
 [95 46  5 53 78]
 [92 24 87 59 91]
 [61 94 65 86 83]
 [23 31 92 33  3]]
Maximum: 95
Minimum: 3
Mean: 60.44
Median: 65.0


In [6]:
# Q6. Create an array of 20 random numbers and sort ascending and descending

import numpy as np

arr = np.random.randint(1, 100, 20)

print("Original Array:", arr)
print("Ascending Order:", np.sort(arr))
print("Descending Order:", np.sort(arr)[::-1])

Original Array: [48 36 67 33 18 49 53  4 98 25 71 83 24 79 24 33 84 60 82 48]
Ascending Order: [ 4 18 24 24 25 33 33 36 48 48 49 53 60 67 71 79 82 83 84 98]
Descending Order: [98 84 83 82 79 71 67 60 53 49 48 48 36 33 33 25 24 24 18  4]


In [7]:
# Q7. Create a 6×6 matrix and print diagonal, upper triangular, lower triangular

import numpy as np

matrix = np.arange(1, 37).reshape(6, 6)

print("Matrix:\n", matrix)
print("Main Diagonal:", np.diag(matrix))
print("Upper Triangular:\n", np.triu(matrix))
print("Lower Triangular:\n", np.tril(matrix))

Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Main Diagonal: [ 1  8 15 22 29 36]
Upper Triangular:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
Lower Triangular:
 [[ 1  0  0  0  0  0]
 [ 7  8  0  0  0  0]
 [13 14 15  0  0  0]
 [19 20 21 22  0  0]
 [25 26 27 28 29  0]
 [31 32 33 34 35 36]]


In [8]:
# Q8. Create an array of 20 elements and reshape it

import numpy as np

arr = np.arange(1, 21)

print("4×5 Matrix:\n", arr.reshape(4, 5))
print("\n2×10 Matrix:\n", arr.reshape(2, 10))
print("\n5×4 Matrix:\n", arr.reshape(5, 4))

4×5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

2×10 Matrix:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

5×4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [9]:
# Q9. Create a 5×5 matrix and calculate row-wise and column-wise sums

import numpy as np

matrix = np.arange(1, 26).reshape(5, 5)

print("Matrix:\n", matrix)
print("Row Sum:", np.sum(matrix, axis=1))
print("Column Sum:", np.sum(matrix, axis=0))

Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Row Sum: [ 15  40  65  90 115]
Column Sum: [55 60 65 70 75]


In [10]:
# Q10. Create two arrays and find common elements

import numpy as np

arr1 = np.array([1,2,3,4,5,6,7])
arr2 = np.array([5,6,7,8,9,10])

print("Common Elements:", np.intersect1d(arr1, arr2))

Common Elements: [5 6 7]
